name = "newsnow"  # 你的项目名称
type = "javascript"
pages_build_output_dir = "dist/output/public"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "5391a8ff-8b04-4631-acf7-d9d5579b274e"      # 替换为你创建的数据库 ID
